/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BetModeSwicher: typeof import('./src/views/home/BetModeSwicher.vue')['default']
    Counter: typeof import('./src/views/home/Counter.vue')['default']
    Detail: typeof import('./src/views/detail/Detail.vue')['default']
    DetailColumn: typeof import('./src/views/detail/DetailColumn.vue')['default']
    Filters: typeof import('./src/views/detail/filters.ts')['default']
    Header: typeof import('./src/views/home/Header.vue')['default']
    Helper: typeof import('./src/views/home/helper.ts')['default']
    HomeView: typeof import('./src/views/home/HomeView.vue')['default']
    Hooks: typeof import('./src/views/detail/hooks.ts')['default']
    Keyboard: typeof import('./src/views/home/Keyboard.vue')['default']
    Listitem: typeof import('./src/views/home/Listitem.vue')['default']
    Matche: typeof import('./src/views/home/Matche.vue')['default']
    Matches: typeof import('./src/views/home/Matches.vue')['default']
    Mock: typeof import('./src/views/detail/mock.ts')['default']
    Odds: typeof import('./src/views/home/Odds.vue')['default']
    OddsColumn: typeof import('./src/views/home/OddsColumn.vue')['default']
    Orders: typeof import('./src/views/home/Orders.vue')['default']
    OrdersEntrance: typeof import('./src/views/home/OrdersEntrance.vue')['default']
    OrdersResult: typeof import('./src/views/home/OrdersResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sticky: typeof import('./src/views/home/Sticky.vue')['default']
    Store: typeof import('./src/views/home/store.ts')['default']
    SVGIcon: typeof import('./src/views/home/SVGIcon.vue')['default']
    Types: typeof import('./src/views/home/types.ts')['default']
    Utils: typeof import('./src/views/utils.ts')['default']
  }
}
