export type Matchs = Match[];
export type Match = Pick<RawMatch, 'leagueLogo' | 'leagueName' | 'matchId' | 'sportTypeId'> & {
  children: RawMatchs;
};

export type RawMatchs = RawMatch[];

export enum MatchStatus {
  Closed = 'closed',
  ClosePrice = 'closePrice',
  Running = 'running',
  Suspend = 'suspend',
}

export const lockedStatusList = [MatchStatus.Closed, MatchStatus.ClosePrice, MatchStatus.Suspend];

export interface Market {
  betType: number;
  marketId: number;
  marketStatus: MatchStatus;
  gameMap: null;
  gameRound: null;
  resourceid: null;
  oddTypeCount: number;
  category: number;
  showCategory: string;
  sort: number;
  selections: Selection[];
  selections2: Selection[];
}

export interface Selection {
  price: string;
  allPrice: AllPrice;
  oddRange: number;
  key: string;
  keyEn: string;
  point: number;
  point2: null;
  decimalPrice: null;
  hongKongPrice: null;
}

export interface AllPrice {
  oddRange: number;
  decimalPrice: number;
  hongKongPrice: number;
}

export interface Order extends Market {
  id: string;
  odds: number;
  point: number;
  matchId: string;
  orderName: string;
}

export interface Detail {
  matchId: string;
  leagueId: string;
  homeId: number;
  awayId: number;
  leagueName: string;
  homeName: string;
  awayName: string;
  eventStatus: MatchStatus;
  runningStatus: string;
  liveHomeScore: number;
  liveAwayScore: number;
  globalShowTime: string;
  sabaStreamViewFlag: string;
  sportTypeId: string;
  sportTypeName: string;
  matchDate: string;
  matchTime: string;
  markets: Market2[];
}

export interface Market2 {
  betType: number;
  gameMap: number;
  betTypeName: string;
  betSelectionGroupNames: string[];
  betSelectionGroupNumber: number;
  marketDataList: MarketDataList[];
}

export interface MarketDataList {
  betType: number;
  marketId: number;
  marketStatus: MatchStatus;
  gameMap: null;
  gameRound: null;
  resourceid: null;
  oddTypeCount: number;
  category: number;
  showCategory: string;
  sort: number;
  selections: Selection[];
  selections2: Selection[];
}

// Generated by https://quicktype.io

export interface Game {
  sportTypeId: string;
  sportTypeName: string;
  totalGames: number;
  inPayGames: number;
  todayGames: number;
  earlyGames: number;
  todayAndTomorrow: number;
  afterTomorrow: number;
  inPayGamesCombo: number;
  todayAndTomorrowCombo: number;
  afterTomorrowCombo: number;
}

// Generated by https://quicktype.io

export interface Live {
  matchId: string;
  leagueId: string;
  homeId: number;
  awayId: number;
  leagueName: string;
  homeName: string;
  homeLogo: string;
  awayName: string;
  awayLogo: string;
  leagueLogo: string;
  eventStatus: string;
  runningStatus: string;
  liveHomeScore: number;
  liveAwayScore: number;
  globalShowTime: string;
  streamSource: number;
  sabaStreamViewFlag: string;
  dawnbyteStreamViewFlag: string;
  sportTypeId: string;
  sportTypeName: string;
  matchDate: string;
  matchTime: string;
  dawnbyteVideoUrl: string;
  dawnbyteVideoUrlList: string;
  inPlayTime: string;
  livePeriod: number;
  inPlayTime2: string;
  totalBetTypeNumber: number;
}

export interface DateTab {
  label: string;
  id: number;
  count: number;
  display: boolean;
}

// Generated by https://quicktype.io

export interface RawMatch {
  matchId: string;
  leagueId: string;
  homeId: number;
  awayId: number;
  leagueName: string;
  homeName: string;
  homeLogo: string;
  awayName: string;
  awayLogo: string;
  leagueLogo: string;
  eventStatus: string;
  runningStatus: string;
  liveHomeScore: number;
  liveAwayScore: number;
  globalShowTime: string;
  streamSource: number;
  sabaStreamViewFlag: string;
  dawnbyteStreamViewFlag: string;
  sportTypeId: string;
  sportTypeName: string;
  matchDate: string;
  matchTime: string;
  dawnbyteVideoUrl: string;
  dawnbyteVideoUrlList: string;
  inPlayTime: string;
  livePeriod: number;
  inPlayTime2: string;
  totalBetTypeNumber: number;
  markets: Market[];
}

export interface SportTab {
  label: string;
  icon: string;
  activeIcon: string;
  count: number;
}
